/**
 * reports.js
 * Purpose: Admin-only report generation and history management.
 * Refactored: Uses Socket.io to match the team's professional backend standard.
 */

(function () {
    const { requireAuth, fmtDate, fmtHeaderDate, getUser } = PAMS;

    let reports = [];
    let activeReportId = null;
    let chart;
    let allUsers = [];

    document.addEventListener('DOMContentLoaded', async () => {
        if (!requireAuth()) return;
        PAMS_UI.init();

        const dateEl = document.getElementById('headerDate');
        if (dateEl) dateEl.textContent = fmtHeaderDate();

        // 1. Initialize Socket Listeners for Reports
        setupSocketListeners();

        // 2. Initial Data Load
        loadReports();
    });

    /**
     * Socket Logic
     */
    function setupSocketListeners() {
        if (!PAMS.socket) {
            console.warn("Socket not initialized. Retrying in 1s...");
            setTimeout(setupSocketListeners, 1000);
            return;
        }

        // Listen for the unified report log event
        PAMS.socket.on('reportLog', (result) => {
            if (!result.success) {
                alert(`Error: ${result.rawData}`);
                return;
            }

            // Handle different stages of the data pipeline
            switch (result.stage) {
                case 'list':
                    reports = result.data || [];
                    renderHistory();
                    if (reports.length > 0 && !activeReportId) {
                        selectReport(reports[0].report_id);
                    }
                    break;
                
                case 'details':
                    renderReportPreview(result.data);
                    break;

                case 'generate':
                    alert(result.rawData || "Report generated successfully!");
                    loadReports(); // Refresh the list
                    break;
            }
        });

        // Listen for real-time broadcasts from other admins
        PAMS.socket.on('reportGenerated', (data) => {
            console.info("Real-time Update: A new report was generated by another admin.");
            loadReports(); // Silently update the history list
        });
    }

    function loadReports() {
        if (CONFIG.USE_MOCK_API) {
            reports = [
                { report_id: 1, report_type: 'Weekly', scope_type: 'All', generated_at: '2026-05-27T08:00:00Z', generated_by_name: 'Admin', period_start: '2026-05-18', period_end: '2026-05-24' },
                { report_id: 2, report_type: 'Daily', scope_type: 'Group', generated_at: '2026-05-20T14:30:00Z', generated_by_name: 'Admin', period_start: '2026-05-11', period_end: '2026-05-17' }
            ];
            renderHistory();
            if (reports.length > 0) selectReport(reports[0].report_id);
            return;
        }

        if (PAMS.socket) {
            PAMS.socket.emit('getReports');
        }
    }

    async function selectReport(id) {
        activeReportId = id;
        renderHistory();

        if (CONFIG.USE_MOCK_API) {
            renderReportPreview([
                { title: 'Process Student Appeals', assignee_name: 'Juan Dela Cruz', historical_status: 'IN PROGRESS', priority: 'URGENT' },
                { title: 'Update Faculty Records', assignee_name: 'Maria Santos', historical_status: 'COMPLETED', priority: 'MEDIUM' }
            ]);
            return;
        }

        if (PAMS.socket) {
            PAMS.socket.emit('getReportDetails', id);
        }
    }

    /**
     * UI Rendering
     */
    function renderHistory() {
        const list = document.getElementById('historyList');
        if (!list) return;

        if (reports.length === 0) {
            list.innerHTML = '<div class="log-empty">No reports generated yet.</div>';
            return;
        }

        list.innerHTML = reports.map(r => `
            <div class="report-card ${r.report_id === activeReportId ? 'active' : ''}" onclick="window.Reports.selectReport(${r.report_id})">
                <div class="report-card-title"><i class="fa-solid fa-file-invoice"></i> ${r.report_type} Report</div>
                <div class="report-card-meta">
                    Generated: ${new Date(r.generated_at).toLocaleDateString()}
                    ${r.generated_by_name ? ` &middot; By: ${r.generated_by_name}` : ''}
                </div>
            </div>
        `).join('');
    }

    function renderReportPreview(tasks) {
        const report = reports.find(r => r.report_id === activeReportId);
        if (!report) return;

        document.getElementById('previewTitle').textContent = `${report.report_type} Accomplishment Report`;
        document.getElementById('previewPeriod').textContent = `Period: ${fmtDate(report.period_start)} – ${fmtDate(report.period_end)} | Scope: ${report.scope_type}`;
        
        // Calculate stats from snapshot data
        const stats = { total: tasks.length, completed: 0, inProgress: 0, pending: 0, cancelled: 0 };
        tasks.forEach(t => {
            const s = (t.historical_status || "").toLowerCase();
            if (s === 'completed') stats.completed++;
            else if (s === 'in progress') stats.inProgress++;
            else if (s === 'pending') stats.pending++;
            else if (s === 'cancelled') stats.cancelled++;
        });

        document.getElementById('statTotal').textContent = stats.total;
        document.getElementById('statCompleted').textContent = stats.completed;
        document.getElementById('statInProgress').textContent = stats.inProgress;

        const statusMap = { 'COMPLETED': 'badge-completed', 'IN PROGRESS': 'badge-in_progress', 'PENDING': 'badge-pending', 'CANCELLED': 'badge-cancelled' };
        const prioMap = { 'URGENT': 'badge-urgent', 'HIGH': 'badge-urgent', 'MEDIUM': 'badge-in_progress', 'LOW': 'badge-pending' };

        const tbody = document.getElementById('taskBody');
        if (tbody) {
            tbody.innerHTML = tasks.length === 0
                ? '<tr><td colspan="4" class="log-empty">No tasks in this report.</td></tr>'
                : tasks.map(t => `
                    <tr>
                        <td class="fw-600">${t.title}</td>
                        <td>${t.assignee_name || '—'}</td>
                        <td><span class="badge ${statusMap[t.historical_status.toUpperCase()] || ''}">${t.historical_status}</span></td>
                        <td><span class="badge ${prioMap[t.priority.toUpperCase()] || ''}">${t.priority}</span></td>
                    </tr>`).join('');
        }

        renderChart(stats);
    }

    function renderChart(stats) {
        const ctxEl = document.getElementById('statusChart');
        if (!ctxEl) return;

        const data = [stats.pending, stats.inProgress, stats.completed, stats.cancelled];
        if (chart) {
            chart.data.datasets[0].data = data;
            chart.update();
        } else {
            chart = new Chart(ctxEl.getContext('2d'), {
                type: 'bar',
                data: {
                    labels: ['Pending', 'In Progress', 'Completed', 'Cancelled'],
                    datasets: [{
                        data,
                        backgroundColor: ['#f59e0b', '#3b82f6', '#16a34a', '#9ca3af'],
                        borderRadius: 6,
                        borderSkipped: false
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    plugins: { legend: { display: false } },
                    scales: {
                        y: { beginAtZero: true, ticks: { stepSize: 1, font: { family: 'Poppins', size: 11 } }, grid: { color: '#f3f4f6' } },
                        x: { ticks: { font: { family: 'Poppins', size: 11 } }, grid: { display: false } }
                    }
                }
            });
        }
    }

    /**
     * Modal Management
     */
    const openModal = (id) => document.getElementById(id)?.classList.add('open');
    const closeModal = (id) => document.getElementById(id)?.classList.remove('open');

    // Export public methods
    window.Reports = {
        openGenerateModal: async () => {
            const today = new Date();
            const monday = new Date(today);
            monday.setDate(today.getDate() - ((today.getDay() + 6) % 7));

            const startInput = document.getElementById('gen-start');
            const endInput = document.getElementById('gen-end');
            if (startInput) startInput.value = monday.toISOString().slice(0, 10);
            if (endInput) endInput.value = today.toISOString().slice(0, 10);

            try {
                if (CONFIG.USE_MOCK_API) {
                    document.getElementById('gen-group').innerHTML = '<option value="1">Student Records</option><option value="2">Admission</option>';
                    allUsers = [{ email: 'juan@pup.edu.ph', name: 'Juan Dela Cruz', code: 'PUP-001' }];
                } else {
                    // We still use REST for these "cold" lookup lists (Groups/Users) to keep it simple
                    const [g, u] = await Promise.all([PAMS.apiFetch('/groups'), PAMS.apiFetch('/users')]);
                    document.getElementById('gen-group').innerHTML = g.groups.map(x => `<option value="${x.id}">${x.name}</option>`).join('');
                    allUsers = u.users || [];
                }
                window.Reports.filterUserResults();
            } catch { }

            window.Reports.clearPickedUser();
            window.Reports.onScopeChange();
            openModal('genModal');
        },
        closeModal: (id) => closeModal(id),
        onScopeChange: () => {
            const scope = document.getElementById('gen-scope').value;
            document.getElementById('gen-group-wrap').style.display = scope === 'Group' ? 'flex' : 'none';
            document.getElementById('gen-user-wrap').style.display = scope === 'Individual' ? 'flex' : 'none';
        },
        filterUserResults: () => {
            const q = (document.getElementById('gen-user-search').value || '').trim().toLowerCase();
            const box = document.getElementById('gen-user-results');
            if (!box) return;

            if (!allUsers.length) {
                box.innerHTML = '<div class="text-xs color-gray text-center py-3">No users loaded.</div>';
                return;
            }

            const matches = (q
                ? allUsers.filter(u =>
                    (u.name || '').toLowerCase().includes(q) ||
                    (u.email || '').toLowerCase().includes(q) ||
                    (u.code || '').toLowerCase().includes(q))
                : allUsers
            ).slice(0, 8);

            if (matches.length === 0) {
                box.innerHTML = '<div class="text-xs color-gray text-center py-3">No matches found.</div>';
                return;
            }

            box.classList.add('open');
            box.innerHTML = matches.map(u => `
                <button type="button" class="user-search-item" onclick="window.Reports.pickUser('${encodeURIComponent(u.email)}','${encodeURIComponent(u.name || u.email)}')">
                    <div class="avatar-sm">${(u.name || '?').charAt(0).toUpperCase()}</div>
                    <div class="user-search-meta">
                        <strong>${u.name || u.email}</strong>
                        <span class="muted">${u.email}${u.code ? ' · ' + u.code : ''}</span>
                    </div>
                </button>`).join('');
        },
        pickUser: (emailEnc, nameEnc) => {
            const email = decodeURIComponent(emailEnc);
            const name = decodeURIComponent(nameEnc);
            document.getElementById('gen-user-email').value = email;
            document.getElementById('gen-user-picked-name').textContent = `${name} (${email})`;
            document.getElementById('gen-user-picked').style.display = 'flex';
            document.getElementById('gen-user-search').style.display = 'none';
            document.getElementById('gen-user-results').classList.remove('open');
        },
        clearPickedUser: () => {
            document.getElementById('gen-user-email').value = '';
            document.getElementById('gen-user-picked').style.display = 'none';
            document.getElementById('gen-user-search').style.display = '';
            document.getElementById('gen-user-search').value = '';
            window.Reports.filterUserResults();
        },
        generateReport: async () => {
            const type = document.getElementById('gen-type').value;
            const scope = document.getElementById('gen-scope').value;
            const start = document.getElementById('gen-start').value;
            const end = document.getElementById('gen-end').value;
            if (!start || !end) { alert('Please set the period.'); return; }

            const me = getUser();
            const body = { 
                reportType: type, 
                scopeType: scope, 
                periodStart: start, 
                periodEnd: end, 
                generatedByEmail: me.email,
                scopeValue: null
            };

            if (scope === 'Group') body.scopeValue = document.getElementById('gen-group').value;
            if (scope === 'Individual') body.scopeValue = document.getElementById('gen-user-email').value;

            if (CONFIG.USE_MOCK_API) {
                const newId = reports.length + 1;
                reports.unshift({ report_id: newId, report_type: type, scope_type: scope, generated_at: new Date().toISOString(), generated_by_name: 'You', period_start: start, period_end: end });
                closeModal('genModal');
                renderHistory();
                selectReport(newId);
                return;
            }

            if (PAMS.socket) {
                PAMS.socket.emit('generateReport', body);
                closeModal('genModal');
            }
        },
        selectReport: (id) => selectReport(id),
        print: () => window.print()
    };
})();
